const express = require('express')

const CheckRouter = require("./checkroute")
const UserValidate = require('./controllers/validate/user')
const EventValidate = require('./controllers/validate/event')
const MemberValidate = require('./controllers/validate/member')
const HomeValidate = require('./controllers/validate/home')
const UserCtrl = require("./controllers/UserCtrl")
const MemberCtrl = require("./controllers/MemberCtrl")
const EventCtrl = require('./controllers/EventCtrl')
const userRouter = express.Router()
userRouter.post('/register', UserValidate.validate('register'), CheckRouter.checkValidateRouter)
userRouter.post('/sendcode',UserValidate.validate('sendcode'),CheckRouter.checkValidateRouter)
userRouter.post('/sendcode1',UserValidate.validate('sendcode1'),CheckRouter.checkValidateRouter)
userRouter.post('/verifycode',UserValidate.validate('verifycode'),CheckRouter.checkValidateRouter)
userRouter.post('/resetpwd',UserValidate.validate('resetpwd'),CheckRouter.checkValidateRouter)
userRouter.post('/login',UserValidate.validate('login'),CheckRouter.checkValidateRouter)
userRouter.get('/signout',UserCtrl.logout)

const eventRouter = express.Router()
eventRouter.get('/getevent',EventValidate.validate('getevent'),CheckRouter.checkValidateRouter)
eventRouter.post('/applyevent',EventValidate.validate('applyevent'),CheckRouter.checkValidateRouter)
eventRouter.post('/payevent',EventValidate.validate('payevent'),CheckRouter.checkValidateRouter)
eventRouter.get('/loadevents',EventCtrl.loadEvents)
eventRouter.get('/photo',EventValidate.validate('photo'),CheckRouter.checkValidateRouter)
eventRouter.post('/setuppay',EventValidate.validate('setuppay'),CheckRouter.checkValidateRouter)
eventRouter.get('/paycallback',EventValidate.validate('paycallback'),CheckRouter.checkValidateRouter)
eventRouter.get('/loadapplicants',EventValidate.validate('loadapplicants'),CheckRouter.checkValidateRouter)
const memberRouter = express.Router()
memberRouter.get('/loadmembers',MemberCtrl.loadMembers)
memberRouter.post('/editmember',MemberValidate.validate('editmember'),CheckRouter.checkValidateRouter)
memberRouter.get('/loadtransactions',MemberValidate.validate('loadtransactions'),CheckRouter.checkValidateRouter)
memberRouter.get('/loadbalance',MemberCtrl.loadBalance)
memberRouter.get('/loadschedule',MemberValidate.validate('loadschedule'),CheckRouter.checkValidateRouter)
memberRouter.get('/loadschedules',MemberValidate.validate('loadschedules'),CheckRouter.checkValidateRouter)
const homeRouter = express.Router()
homeRouter.get('/loadresources',HomeValidate.validate('loadresources'),CheckRouter.checkValidateRouter)
homeRouter.get('/photo',HomeValidate.validate('photo'),CheckRouter.checkValidateRouter)
module.exports = {userRouter,eventRouter,memberRouter,homeRouter}